% ==============================================================================
% create_RobotSimulation.m  -  Fixed Version (Works on MATLAB Online)
%
% This file is the only one required for model creation.
% No need for robot_sfunc.m - replaced by a MATLAB Function block.
%
% To Run:
%   >> create_RobotSimulation
% ==============================================================================

clear; clc;

mdl     = 'RobotSimulation';
outFile = fullfile(pwd, [mdl '.slx']);

%% ---- Close and delete old versions ------------------------------------------
if bdIsLoaded(mdl),       close_system(mdl, 0); end
if exist(outFile,'file'), delete(outFile);       end

%% ---- Create new empty model -------------------------------------------------
new_system(mdl);
open_system(mdl);

%% ---- Simulation settings ----------------------------------------------------
set_param(mdl, ...
    'StopTime',   '25',         ...
    'SolverType', 'Fixed-step', ...
    'FixedStep',  '0.05',       ...
    'Solver',     'ode3');

%% ---- Block positions --------------------------------------------------------
SRC_W = 100; SRC_H = 35; SRC_X = 40;
Y = @(n) 50 + (n-1)*65;

FCN   = [230  50  480 430];
SCOPE = [550  80  620 210];
DISL  = [550 230  690 265];
DISR  = [550 280  690 315];
WKSL  = [550 330  690 365];
WKSR  = [550 380  690 415];

%% ---- Source blocks ----------------------------------------------------------
add_block('simulink/Sources/Constant',[mdl '/Distance_cm'], ...
    'Value','30','Position',[SRC_X,Y(1),SRC_X+SRC_W,Y(1)+SRC_H]);

sensors = {'L2','L1','R1','R2'};
senVals = {'1','0','0','1'};
for k = 1:4
    add_block('simulink/Sources/Constant',[mdl '/' sensors{k}], ...
        'Value',senVals{k}, ...
        'Position',[SRC_X,Y(k+1),SRC_X+SRC_W,Y(k+1)+SRC_H]);
end

add_block('simulink/Sources/Clock',[mdl '/SimClock'], ...
    'Position',[SRC_X,Y(6),SRC_X+SRC_W,Y(6)+SRC_H]);

%% ---- MATLAB Function Block -------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [mdl '/RobotController'],'Position',FCN);

%% ---- Writing controller code via Stateflow API ----------------------------
rt    = sfroot();
chart = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/RobotController']);

nl = newline;
chart.Script = [...
'function [outLeft, outRight] = fcn(distance, l2, l1, r1, r2, currentTime)' nl ...
'persistent st spd trn lim llst lltout utst uttm avst avFlag lpwm rpwm;' nl ...
'if isempty(st)' nl ...
'    st=int32(0); spd=160; trn=130; lim=20;' nl ...
'    llst=0; lltout=1.5; utst=0; uttm=1.2;' nl ...
'    avst=0; avFlag=true; lpwm=0; rpwm=0;' nl ...
'end' nl ...
'EXPL=int32(0); RETN=int32(1); DONE=int32(2);' nl ...
'' nl ...
'if st==DONE' nl ...
'    [outLeft,outRight]=doStop(); lpwm=outLeft; rpwm=outRight; return;' nl ...
'end' nl ...
'' nl ...
'if distance>0 && distance<lim && ~avFlag' nl ...
'    avst=currentTime; avFlag=true;' nl ...
'end' nl ...
'' nl ...
'if avFlag' nl ...
'    t=currentTime-avst;' nl ...
'    if    t<0.5, [outLeft,outRight]=doStop();' nl ...
'    elseif t<1.5,[outLeft,outRight]=doRight(trn);' nl ...
'    elseif t<2.5,[outLeft,outRight]=doFwd(spd);' nl ...
'    elseif t<3.0,[outLeft,outRight]=doLeft(trn);' nl ...
'    else,        avFlag=false; avst=0; [outLeft,outRight]=doFwd(spd);' nl ...
'    end' nl ...
'    lpwm=outLeft; rpwm=outRight; return;' nl ...
'end' nl ...
'' nl ...
'isX=(l2==0 && r2==0);' nl ...
'if    l1==0&&r1==0, pos= 0;' nl ...
'elseif l1==0&&r1==1,pos=-1;' nl ...
'elseif r1==0&&l1==1,pos= 1;' nl ...
'elseif l2==0,       pos=-2;' nl ...
'elseif r2==0,       pos= 2;' nl ...
'else,               pos=99;' nl ...
'end' nl ...
'' nl ...
'if st==RETN && isX' nl ...
'    st=DONE; [outLeft,outRight]=doStop();' nl ...
'    lpwm=outLeft; rpwm=outRight; return;' nl ...
'end' nl ...
'' nl ...
'if pos==0' nl ...
'    [outLeft,outRight]=doFwd(spd); llst=0;' nl ...
'elseif pos==-1||pos==-2' nl ...
'    [outLeft,outRight]=doLeft(trn); llst=0;' nl ...
'elseif pos==1||pos==2' nl ...
'    [outLeft,outRight]=doRight(trn); llst=0;' nl ...
'else' nl ...
'    if llst==0, llst=currentTime; end' nl ...
'    if currentTime-llst > lltout' nl ...
'        if st==EXPL' nl ...
'            if utst==0, utst=currentTime; end' nl ...
'            dt=currentTime-utst;' nl ...
'            if    dt<0.5,         [outLeft,outRight]=doStop();' nl ...
'            elseif dt<0.5+uttm,   [outLeft,outRight]=doRight(trn);' nl ...
'            else, st=RETN; utst=0; [outLeft,outRight]=doStop();' nl ...
'            end' nl ...
'        else' nl ...
'            st=DONE; [outLeft,outRight]=doStop();' nl ...
'        end' nl ...
'    else' nl ...
'        outLeft=lpwm; outRight=rpwm;' nl ...
'    end' nl ...
'end' nl ...
'lpwm=outLeft; rpwm=outRight;' nl ...
'end' nl ...
'' nl ...
'function [L,R]=doStop(),  L=0;   R=0;   end' nl ...
'function [L,R]=doFwd(s),  L=s;   R=s;   end' nl ...
'function [L,R]=doLeft(s), L=-s;  R=s;   end' nl ...
'function [L,R]=doRight(s),L=s;   R=-s;  end' nl ...
];

%% ---- Output blocks ----------------------------------------------------------
add_block('simulink/Sinks/Scope',[mdl '/PWM_Scope'], ...
    'NumInputPorts','2','Position',SCOPE);
add_block('simulink/Sinks/Display',[mdl '/Left_PWM'],'Position',DISL);
add_block('simulink/Sinks/Display',[mdl '/Right_PWM'],'Position',DISR);
add_block('simulink/Sinks/To Workspace',[mdl '/LeftPWM_WS'], ...
    'VariableName','leftPWM_out','MaxDataPoints','inf', ...
    'SaveFormat','Array','Position',WKSL);
add_block('simulink/Sinks/To Workspace',[mdl '/RightPWM_WS'], ...
    'VariableName','rightPWM_out','MaxDataPoints','inf', ...
    'SaveFormat','Array','Position',WKSR);

%% ---- Connection lines ------------------------------------------------------
src = {'Distance_cm','L2','L1','R1','R2','SimClock'};
for k = 1:6
    add_line(mdl,[src{k} '/1'],['RobotController/' num2str(k)], ...
        'autorouting','on');
end
add_line(mdl,'RobotController/1','Left_PWM/1',   'autorouting','on');
add_line(mdl,'RobotController/2','Right_PWM/1',  'autorouting','on');
add_line(mdl,'RobotController/1','PWM_Scope/1',  'autorouting','on');
add_line(mdl,'RobotController/2','PWM_Scope/2',  'autorouting','on');
add_line(mdl,'RobotController/1','LeftPWM_WS/1', 'autorouting','on');
add_line(mdl,'RobotController/2','RightPWM_WS/1','autorouting','on');

%% ---- Save model -----------------------------------------------------------
save_system(mdl, outFile);

fprintf('\n✅ RobotSimulation.slx created successfully!\n');
fprintf('   Path : %s\n\n', outFile);
fprintf('   To open model   : open_system(''%s'')\n', mdl);
fprintf('   To run simulation: sim(''%s'')\n\n', mdl);
